[versions]
jdk = "8"
checkstyle = "8.45.1"

[plugins]
git-publish = "org.ajoberstar.git-publish:3.0.1" # max for jdk8
pages = "com.hendraanggrian.pages:0.1"

[libraries]
# lint
rulebook-checkstyle = "com.hendraanggrian.rulebook:rulebook-checkstyle:0.3"
# main
# test
truth = "com.google.truth:truth:1.1.5"
